# Generated by Django 4.0.5 on 2022-07-24 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Category_name', models.CharField(choices=[('Family', 'Fam'), ('Couple', 'Cpl'), ('Solo', 'Sol'), ('Children', 'Kid')], max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('Event_Id', models.IntegerField(primary_key=b'I01\n', serialize=False)),
                ('Event_Name', models.CharField(max_length=30)),
                ('Event_Cost', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('Date', models.DateField(blank=True)),
                ('Capacity', models.IntegerField(default=30)),
                ('CurrentCapacity', models.IntegerField(default=30)),
                ('Event_image', models.ImageField(upload_to='')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Event_Category', to='events.category')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('Location_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Country', models.CharField(max_length=20)),
                ('Region', models.CharField(blank=True, choices=[('Europe', 'Eu'), ('Asia', 'As'), ('Oceania', 'Oce'), ('Africa', 'Afr'), ('N.America', 'NAm'), ('S.America', 'SAm')], max_length=15)),
                ('NumberofEvents', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('SubCategory_name', models.CharField(choices=[('VIP', 'VIP'), ('Expensive', 'Exp'), ('Cheap', 'chp'), ('Free', 'Fr')], max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=b'I01\n', serialize=False)),
                ('first', models.CharField(default='Unknown', max_length=64)),
                ('last', models.CharField(default='Unknown', max_length=64)),
                ('Age', models.IntegerField()),
                ('phone', models.IntegerField(default=0)),
                ('mail', models.EmailField(default='@', max_length=254)),
                ('admin_status', models.BooleanField(default=False)),
                ('events', models.ManyToManyField(blank=True, related_name='registered_users', to='events.events')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='Event_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Event_Location', to='events.location'),
        ),
        migrations.AddField(
            model_name='category',
            name='SubCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubCategory', to='events.subcategory'),
        ),
    ]
